/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ResenhaRouteImport } from './routes/resenha'
import { Route as JogosRouteImport } from './routes/jogos'
import { Route as HorariosRouteImport } from './routes/horarios'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as EstruturaRouteImport } from './routes/estrutura'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminSorteioRouteImport } from './routes/_authenticated/admin/sorteio'
import { Route as AuthenticatedAdminMensalistasRouteImport } from './routes/_authenticated/admin/mensalistas'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ResenhaRoute = ResenhaRouteImport.update({
  id: '/resenha',
  path: '/resenha',
  getParentRoute: () => rootRouteImport,
} as any)
const JogosRoute = JogosRouteImport.update({
  id: '/jogos',
  path: '/jogos',
  getParentRoute: () => rootRouteImport,
} as any)
const HorariosRoute = HorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const EstruturaRoute = EstruturaRouteImport.update({
  id: '/estrutura',
  path: '/estrutura',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminSorteioRoute =
  AuthenticatedAdminSorteioRouteImport.update({
    id: '/admin/sorteio',
    path: '/admin/sorteio',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminMensalistasRoute =
  AuthenticatedAdminMensalistasRouteImport.update({
    id: '/admin/mensalistas',
    path: '/admin/mensalistas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/estrutura': typeof EstruturaRoute
  '/eventos': typeof EventosRoute
  '/horarios': typeof HorariosRoute
  '/jogos': typeof JogosRoute
  '/resenha': typeof ResenhaRoute
  '/sobre': typeof SobreRoute
  '/admin/mensalistas': typeof AuthenticatedAdminMensalistasRoute
  '/admin/sorteio': typeof AuthenticatedAdminSorteioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/estrutura': typeof EstruturaRoute
  '/eventos': typeof EventosRoute
  '/horarios': typeof HorariosRoute
  '/jogos': typeof JogosRoute
  '/resenha': typeof ResenhaRoute
  '/sobre': typeof SobreRoute
  '/admin/mensalistas': typeof AuthenticatedAdminMensalistasRoute
  '/admin/sorteio': typeof AuthenticatedAdminSorteioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/estrutura': typeof EstruturaRoute
  '/eventos': typeof EventosRoute
  '/horarios': typeof HorariosRoute
  '/jogos': typeof JogosRoute
  '/resenha': typeof ResenhaRoute
  '/sobre': typeof SobreRoute
  '/_authenticated/admin/mensalistas': typeof AuthenticatedAdminMensalistasRoute
  '/_authenticated/admin/sorteio': typeof AuthenticatedAdminSorteioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/estrutura'
    | '/eventos'
    | '/horarios'
    | '/jogos'
    | '/resenha'
    | '/sobre'
    | '/admin/mensalistas'
    | '/admin/sorteio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/estrutura'
    | '/eventos'
    | '/horarios'
    | '/jogos'
    | '/resenha'
    | '/sobre'
    | '/admin/mensalistas'
    | '/admin/sorteio'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/estrutura'
    | '/eventos'
    | '/horarios'
    | '/jogos'
    | '/resenha'
    | '/sobre'
    | '/_authenticated/admin/mensalistas'
    | '/_authenticated/admin/sorteio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  EstruturaRoute: typeof EstruturaRoute
  EventosRoute: typeof EventosRoute
  HorariosRoute: typeof HorariosRoute
  JogosRoute: typeof JogosRoute
  ResenhaRoute: typeof ResenhaRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resenha': {
      id: '/resenha'
      path: '/resenha'
      fullPath: '/resenha'
      preLoaderRoute: typeof ResenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogos': {
      id: '/jogos'
      path: '/jogos'
      fullPath: '/jogos'
      preLoaderRoute: typeof JogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horarios': {
      id: '/horarios'
      path: '/horarios'
      fullPath: '/horarios'
      preLoaderRoute: typeof HorariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estrutura': {
      id: '/estrutura'
      path: '/estrutura'
      fullPath: '/estrutura'
      preLoaderRoute: typeof EstruturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/sorteio': {
      id: '/_authenticated/admin/sorteio'
      path: '/admin/sorteio'
      fullPath: '/admin/sorteio'
      preLoaderRoute: typeof AuthenticatedAdminSorteioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/mensalistas': {
      id: '/_authenticated/admin/mensalistas'
      path: '/admin/mensalistas'
      fullPath: '/admin/mensalistas'
      preLoaderRoute: typeof AuthenticatedAdminMensalistasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminMensalistasRoute: typeof AuthenticatedAdminMensalistasRoute
  AuthenticatedAdminSorteioRoute: typeof AuthenticatedAdminSorteioRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminMensalistasRoute: AuthenticatedAdminMensalistasRoute,
  AuthenticatedAdminSorteioRoute: AuthenticatedAdminSorteioRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  EstruturaRoute: EstruturaRoute,
  EventosRoute: EventosRoute,
  HorariosRoute: HorariosRoute,
  JogosRoute: JogosRoute,
  ResenhaRoute: ResenhaRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
